<a href="https://colab.research.google.com/github/Anveshkh/Tensorflow-fundamentals/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we're going to cover some of the most fundamental concepts of tensors using Tensorflow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Maniputating tensors
* Tensors and numpy
* Using !tf.function (a way to speed up your regular python functions)
* Using GPUs with Tensorflow (or TPUs)
* Exercises to try for yourself

# Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
scalar.ndim

0

In [ ]:
vector.ndim

1

In [ ]:
 # Create a matrix
 matrix = tf.constant([[1,2], [3, 4]])
 matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
 matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

what we've created so far
* Scalar : A scalar is a single number
* Vector : A number with direction (e.g. wind speed and direction)
* Matrix : A 2-dimentional array of numbers
* Tensor : An n-dimentional array of numbers (when n can be any number, a 0-dimentional tensor is a scalar, a 1-dimentional tensor is a vector)


## Creating tensors with tf.Variable

In [ ]:
# Create the same tensor with tf.Variable() as above
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# changable_tensor[0] = 98

In [ ]:
# How about we try .assign()
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try to change our unchangable tensor
# unchangable_tensor[0].assign(89)


# Creating Random Tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [ ]:
# Create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of elements in the tensor

In [ ]:
# Shuffle a tensor valueable for when you want to shuffle your data so that the
# inherent order does not affect the predictions
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Shuffle our non-shuffled tensor
shuffled_tensor = tf.random.shuffle(not_shuffled)
shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# Here we are getting the same answer every time we rerun our cell

tf.random.set_seed(42)
shuffled_tensor_2 = tf.random.shuffle(not_shuffled)
shuffled_tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

# Reason why we shuffle

If we're trying to build a food image classifcation network and we had 15000 images of food where 10000 images are of Ramen and 5000 images of Spaghetti.
But our Neural network saw 10000 images of Ramen first the patterns that it may have learned may be too aligned towards Ramen Image rather than a Speghetti image
that's why we may want to shuffle the order of our images so that the patterns that our neural network learns are tuned to both Ramen and Speghetti

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed.

In [ ]:
# Other ways to make tensors

tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

The main difference between Numpy arrays and Tensorflow tensors is that tensors
can be run on a GPU computing.

Capital for matrix or tensor.
Non-capital for vector

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Creates a numpy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A, shape=(2,4,3))
B

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

 # Getting Information from tensors

In [ ]:
# Shape => The number of elements of each of the dimentions of a tensor
A.shape

TensorShape([24])

In [ ]:
# Rank => The number of tensor dimentions. A scalar has rank 0, a vector has rank  1, a matrix is rank 2, a tensor is rank n.
A.ndim

1

In [ ]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
A.shape

TensorShape([24])

In [ ]:
B.shape

TensorShape([2, 4, 3])

In [ ]:
B.ndim

3

In [ ]:
B, tf.size(B)

(<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [ ]:
 # Create a rank 4 tensor (4 dimentions)
 rank_3_tensor = tf.zeros(shape=(3, 4, 5)) # 3 layers of 4 rows and 5 columns
 rank_3_tensor

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
 arr1 = np.arange(5, 15)
 arr1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr1_tensor = tf.constant(arr1)
arr1_tensor
arr1_tensor_2d = tf.constant(arr1, shape=(5,2))
arr1_tensor_2d

<tf.Tensor: shape=(5, 2), dtype=int64, numpy=
array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("The datatype of every element : ", rank_4_tensor.dtype)
print("Number of dimensions (rank) : ", rank_4_tensor.ndim)
print("Shape of tensor : ", rank_4_tensor.shape)
print("Elements along the 0 axis : ", rank_4_tensor.shape[0])
print("Elements along the last axis : ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor : ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor : ", tf.size(rank_4_tensor).numpy())

The datatype of every element :  <dtype: 'float32'>
Number of dimensions (rank) :  4
Shape of tensor :  (2, 3, 4, 5)
Elements along the 0 axis :  2
Elements along the last axis :  5
Total number of elements in our tensor :  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor :  120


# Indexing tensors
Tensors can be indexed just like Python lists

In [ ]:
# Get the first 2 elements of each dimention
rank_4_tensor.ndim, rank_4_tensor.shape

(4, TensorShape([2, 3, 4, 5]))

In [ ]:
# This is an array
one = np.zeros(shape=[3,3],dtype=np.int16)
one

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [ ]:
one_tensor = tf.Variable(one, shape=[3,3])
one_tensor

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int16, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)>

In [ ]:
print("Total number of elements in our tensor : ", tf.size(one_tensor).numpy())

Total number of elements in our tensor :  9


In [ ]:
one_tensor[:2]

<tf.Tensor: shape=(2, 3), dtype=int16, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)>

In [ ]:
one_tensor[0][:2]

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([0, 0], dtype=int16)>

In [ ]:
rand_tensor = np.arange(1, 25)
rand_tensor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
two_tensor = tf.constant(rand_tensor, shape=(6,4))
two_tensor

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

In [ ]:
two_tensor[3:], two_tensor[:4], two_tensor[2:4]

(<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])>,
 <tf.Tensor: shape=(4, 4), dtype=int64, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])>,
 <tf.Tensor: shape=(2, 4), dtype=int64, numpy=
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])>)

In [ ]:
two_tensor[3][-2:]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([15, 16])>

In [ ]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first 2 elements of each dimension
# rank_4_tensor[:2, :2, :2, :2]
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
ek = tf.constant([1,2,3,4,5,6], shape=(3,2))
ek

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
new_ek = tf.reshape(ek, shape=[6,1])
new_ek

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
# Rank === dimensions
rank_2_tensor = tf.constant([11,22,33,44,55,66,77,88,99], shape=(3,3))
rank_2_tensor.ndim

2

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]], dtype=int32)>

In [ ]:
rank_2_tensor2 = tf.constant([[10,7], [3,4]])
rank_2_tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
rank_2_tensor3 = tf.constant([10,7,3,4], shape=(2,2))
rank_2_tensor3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor3[:, -1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor, rank_3_tensor.shape, rank_2_tensor3.shape, rank_3_tensor.ndim

(<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
 array([[[11],
         [22],
         [33]],
 
        [[44],
         [55],
         [66]],
 
        [[77],
         [88],
         [99]]], dtype=int32)>,
 TensorShape([3, 3, 1]),
 TensorShape([2, 2]),
 3)

# Manipulating tensors (tensor operations)

**Basic Operations**
`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor1 = tf.constant([[10,7], [3,4]])
tensor1 + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]],

       [[130, 140, 150],
        [160, 170, 180]]], dtype=int32)>

In [ ]:
tensor1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor1 - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tensorflow builtin function too
tf.multiply(tensor1, tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

## **Matrix Multiplication**

In [ ]:
print(tensor1)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [ ]:
tf.linalg.matmul(tensor1, tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tf.matmul(tensor1, tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python using operator '@'
tensor1 @ tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

# To multiply a matrix this is the specified condition

Number of columns in first matrix should be equal to number of rows in second matrix

In [ ]:
# Creating first tensor
t1 = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
t1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
# Creating second tensor
t2 = tf.constant([[11,12], [13,14], [15,16]])
t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14],
       [15, 16]], dtype=int32)>

In [ ]:
t1 @ t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 82,  88],
       [199, 214],
       [316, 340]], dtype=int32)>

In [ ]:
tf.linalg.matmul(t1, t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 82,  88],
       [199, 214],
       [316, 340]], dtype=int32)>

In [ ]:
tf.transpose(t2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 13, 15],
       [12, 14, 16]], dtype=int32)>

## The DOT product

Matrix multiplication is also referred to as the dot product
You can perform matrix multiplication using
* tf.matmul()
* tf.tensordot()

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)

X = tf.constant([[1,2], [3,4], [5,6]])
Y = tf.constant([[7,8], [9,10], [11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## **Changing the datatype of tensors**

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.2, 34])
B.dtype

tf.float32

In [ ]:
C = tf.constant([3,2])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float 16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B.dtype, B

(tf.float16,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 1.2, 34. ], dtype=float16)>)

In [ ]:
# Change from int32 to float 32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 2.], dtype=float32)>,
 tf.float32)

In [ ]:
# Change from float 16 to int32
F = tf.cast(B, dtype=tf.int32)
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 34], dtype=int32)>

## **Aggregating tensors**

Aggregating tensors = Reducing them from multiple values down to a smaller amount of values.
OR
Combining the smaller parts to form a bigger part

In [ ]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation :
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
tensor = tf.constant([1,2,3,4,5,6,7,8,150], shape=(3,3))
# tensor
print("The mean of tensor is  : ",tf.reduce_mean(tensor).numpy())
print("The maximum value in tensor is : " ,tf.reduce_max(tensor).numpy())
print("The minimum value in tensor is : ", tf.reduce_min(tensor).numpy())
print("The sum of the given tensor is : ", tf.reduce_sum(tensor).numpy())

The mean of tensor is  :  20
The maximum value in tensor is :  150
The minimum value in tensor is :  1
The sum of the given tensor is :  186


In [ ]:
arr = np.random.randint(0,100, size=50)
arr
random_tensor = tf.constant(arr)
random_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([25, 62, 19, 16, 42, 57, 22, 77, 37, 93, 31, 55, 13,  2,  9, 47, 73,
       70, 71, 47, 52, 27, 23, 14, 95, 98, 19, 98, 46,  9, 95,  4, 17, 31,
       48, 64, 21, 44, 87, 39,  7, 56, 63, 48,  5, 29, 11, 74, 56, 45])>

In [ ]:
tf.size(random_tensor).numpy()

50

In [ ]:
tf.shape(random_tensor).numpy()

array([50], dtype=int32)

In [ ]:
random_tensor.ndim

1

In [ ]:
# std_deviation = tf.math.reduce_std(random_tensor)
new_random_tensor = tf.cast(random_tensor, dtype = tf.float32)
new_random_tensor.dtype

tf.float32

In [ ]:
tf.math.reduce_std(new_random_tensor).numpy()

27.735184

In [ ]:
tf.math.reduce_variance(new_random_tensor).numpy()

769.2404

In [ ]:
# tf.reduce_variance(new_random_tensor).numpy()
tf.math.reduce_variance(tf.cast(random_tensor, dtype=tf.float32)).numpy()

769.2404

## Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
# Returns the index of the largest element in the array
tf.argmax(F)


<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the minimum using positional minimum
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Sqeezing a tensor(Removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
# Sqeeze => Removes dimensions of size 1 from the shape of the tensor
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

## One Hot Encoding Tensors

In [ ]:
# Create a list of indices
some_list = [0,1,2,3] # could be red,  green, blue, purple
# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
 tf.one_hot(some_list, depth=4, on_value="Yo I love you", off_value="I don't love you")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo I love you', b"I don't love you", b"I don't love you",
        b"I don't love you"],
       [b"I don't love you", b'Yo I love you', b"I don't love you",
        b"I don't love you"],
       [b"I don't love you", b"I don't love you", b'Yo I love you',
        b"I don't love you"],
       [b"I don't love you", b"I don't love you", b"I don't love you",
        b'Yo I love you']], dtype=object)>

In [ ]:
tf.one_hot(some_list, depth=4, on_value="You're on", off_value="Fuckoff")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"You're on", b'Fuckoff', b'Fuckoff', b'Fuckoff'],
       [b'Fuckoff', b"You're on", b'Fuckoff', b'Fuckoff'],
       [b'Fuckoff', b'Fuckoff', b"You're on", b'Fuckoff'],
       [b'Fuckoff', b'Fuckoff', b'Fuckoff', b"You're on"]], dtype=object)>

### Tensors and numpy

In [ ]:
# Create a tensor directly from numpy array
a = np.array([1,2,3])
A = tf.constant(a)
A, type(A)

(<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>,
 tensorflow.python.framework.ops.EagerTensor)

In [ ]:
# Convert our tensor back to a Numpy array
b = np.array(A)
type(b)

numpy.ndarray

In [ ]:
# If we create a tensor from an numpy array the default type is float64
# If we create a tensor from an python list the default type of tensor is float 32

numpy_tensor = tf.constant(np.array([1,2,3]))
list_tensor = tf.constant([1,2,3])
numpy_tensor.dtype, list_tensor.dtype

(tf.int64, tf.int32)

In [ ]:
numpy_ten = tf.constant(np.array([1., 2., 3.]))
list_ten = tf.constant([1., 2., 3.])
numpy_ten.dtype, list_tensor.dtype

(tf.float64, tf.int32)